/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMEMO, IMEMOInterface } from "../IMEMO";

const _abi = [
  {
    inputs: [],
    name: "index",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMEMO__factory {
  static readonly abi = _abi;
  static createInterface(): IMEMOInterface {
    return new utils.Interface(_abi) as IMEMOInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMEMO {
    return new Contract(address, _abi, signerOrProvider) as IMEMO;
  }
}
