/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITimeBondDepository,
  ITimeBondDepositoryInterface,
} from "../ITimeBondDepository";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxPrice",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_depositor",
        type: "address",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITimeBondDepository__factory {
  static readonly abi = _abi;
  static createInterface(): ITimeBondDepositoryInterface {
    return new utils.Interface(_abi) as ITimeBondDepositoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimeBondDepository {
    return new Contract(address, _abi, signerOrProvider) as ITimeBondDepository;
  }
}
